version: '3.8'
services:
  echowear-gui:
    build: .
    container_name: echowear-gui
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./demo_paths:/app/demo_paths
      - ./models:/app/models
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    stdin_open: true
    tty: true
    # Uncomment the following if you want to use PulseAudio instead of ALSA
    # environment:
    #   - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    # volumes:
    #   - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    #   - /run/user/1000/pulse:/run/user/1000/pulse

  echowear-test:
    build: .
    container_name: echowear-test
    command: bash -c "python smoke_test.py && python pressure_test.py"
    volumes:
      - ./demo_paths:/app/demo_paths
      - ./models:/app/models
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    stdin_open: true
    tty: true
